app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, render_template, redirect, request, url_for 
from flask_login import login_required, login_user, logout_user

from . import home
from .. import db
from ..models import Student, Professional, organisation, Interests, locations

@home.route ('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('signin.html')

@home.route('/login',methods=['GET', 'POST'])
def login():
    if request.method == "POST": 

        student = Student.query.filter_by(email= request.form.get("contact")).first()

        if student is not None and student.verify_password(request.form.get("password")):
            login_user(student)
            return redirect(url_for('student.home'))
        else:
            flash('Invalid email or password.')

    return render_template('home.html')

@home.route('/register')
def register():
    return render_template('signup.html')

@home.route('/register/student', methods=['GET', 'POST'])
def student_register():
    if request.method == "POST":    
        
        # input_interest = Interests.query.filter_by(description=request.form.get("interests")).one()
        interest_in_mentor = request.form.get("Mentor")
        student = Student(name = request.form.get("name"),
                    username = request.form.get("surname"),
                    # interests = input_interest,
                    email = request.form.get("contact"),   
                    password = request.form.get("password"),
                    level = request.form.get("password"),
                    mentorship = True if interest_in_mentor == 'Yes' else False)

        db.session.add(student)
        db.session.commit()

        print("Added student")

        return redirect(url_for('student.student_home'))

     # load student registration template
    return render_template('student.html')

@home.route('/register/professional', methods=['GET', 'POST'])
def professional_register():
    if request.method == "POST":
    #todo: add progessional object to db 
        return redirect(url_for('professional.professional_home'))

    return render_template('mentor.html')

@home.route('/register/institution', methods=['GET', 'POST'])
def institution_register():
    if request.method == "POST":
        #todo: add institution object to db 
        return redirect(url_for('institution.institution_home'))
    return render_template('institution.html')

@home.route('/logout')
@login_required
def logout():
    #add log out details
    logout_user()
    return redirect(url_for('home.login'))

app/institution/__init__.py
from flask import Blueprint

institution = Blueprint('institution', __name__)

from . import views

app/institution/views.py
from flask import abort, render_template, redirect

from . import institution


@institution.route('/home')
def institution_home():
    return render_template('institutionHome.html')

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/student/views.py
from flask import abort, render_template, redirect

from . import student

@student.route('/<username>')
def student_profile(name):
    
    #would have preferred a unique identifier such as username

    student = Student.query.filter_by(name=name).first() 
    return 'this is a student profile'

@student.route('/home')
def student_home():
    return render_template('home.html')

@student.route('/network')
def network():
    return render_template('network.html')

app/templates/MentorHome.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 30%;">
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">Contact us |</a>
      <a href="{{url_for('home.register')}}" style="color: white;">Log out</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>

        <div style="position: fixed;
         bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;">
          <div class="container" style=" width: 60%; padding-right: 5px; border-radius: 25px; border-width: thin; border-style: solid; margin-top: 2%;">
            <div class="container" style="width: 100%; padding: 10% 5%;">

              <h2 style="text-align: center;">Your current Mentees</h2>
              <label>Name: </label>
            </br>
            <label>Name: </label>
          </br>
          <label>Name: </label>
          <div class="d-flex justify-content-center">

            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black;">Chat</button>
            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black;">Add new mentee</button>
          </div>
              </div>
              </div>
        </div>

        <div style="position: fixed;
        bottom: 2%;
        right: 3%;
        width: 50%;
        height: 90%;
        background-color: #f2f2f2;">
           <div style="position: fixed;
           top: 10%;
           right: 7%;
          width: 40%;
           height: 5%;
           background-color: #FF7994;text-align: center;
           font-size:xx-large;">
            WELCOME MENTOR
           </div>
 
           <div style="position: fixed;
           top: 16%;
           right: 7%;
          width: 40%;
           height: 5%;
           background-color: #FF7994;text-align: center;
           font-size:xx-large;">
            CURRENT OPPORTUNITIES
           </div>
 
         <div style="position: fixed;
         top: 23%;
         right: 11%;
        width: 30%;
         height: 25%;
         text-align: center;
         border-style: solid;
         border-color: black;
         border-radius: 10%">
         
         </div>
 
         <div style="position: fixed;
         top: 50%;
         right: 11%;
         width: 30%;
         height: 25%;
         text-align: center;
         border-style: solid;
         border-color: black;
         border-radius: 10%">
         
         </div>
        </div>
      </body>

</html>

app/templates/company.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 20%;">
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
      <a href="{{url_for('home.register')}}" style="color: white;">Contact us</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>

        <div style="position: fixed;
              bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;">
          <div style="position: fixed; left: 15%; width: 50%; height: 45%;" >
            <img src="{{url_for('static', filename='Company.png')}}" align="centre" style="width:400px;height:400px;" />
          </div>
        </div>

        <div style="position: fixed;
        bottom: 2%;
        right: 3%;
        width: 50%;
        height: 90%;
        background-color: #f2f2f2;">
           <div style="position: fixed;
              bottom: 2%;
              right: 3%;
              width: 50%;
              height: 90%;
              background-color: #f2f2f2;
              text-align: center;">
               <div style="position: fixed;
               top: 10%;
               right: 7%;
              width: 40%;
               height: 5%;
               background-color: #FF7994;text-align: center;
               font-size:xx-large;">
                COMPANY SIGN-UP
               </div>
              <div class="container" style=" width: 80%; padding: 2em; border-radius: 25px; border-width: thin; border-style: solid; margin-top: 10%;">
                <div class="container" style="width: 100%; padding: 5% 5%;">

                  <form action="{{ url_for('home.institution_register') }}" method="POST">
                    <div class="form-group">
                      <input type="text" class="form-control" name="name" placeholder="Name">
                    </div>              

                    <div class="form-group">
                      <input type="text" class="form-control" name="website" placeholder="Website">
                    </div>

                    <div class="form-group">
                        <label for="Category">Description: </label>
                        <br>
                        <textarea class="container" name="about" rows="5" cols="40">
                    </textarea>
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="email" placeholder="Email">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="location" placeholder="Location">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="password" placeholder="Password">
                    </div>

                                     </div>
                    <div class="form-group">
                      <label for="Field">Field: </label>
                      <select class="form-group col-3" name="tag">
                        <option type="checkbox" id="tag1" name="tag1">
                        <label for="tag1"> Science</label>
                        <option type="checkbox" id="tag2" name="tag2">
                        <label for="tag2"> Mathematics</label>
                        <option type="checkbox" id="tag3" name="tag3">
                        <label for="tag3"> Economics</label>
                        <option type="checkbox" id="tag4" name="tag4">
                        <label for="tag4"> Physics</label>
                      </select>
                    </div>

                    <div class="d-flex justify-content-center">

                      <button type="submit" class="btn btn-info" style="margin-top: 2%;">SIGN UP</button>
                    </div>

                  </form>
                </div>
        </div>
      </body>

</html>

app/templates/home.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 30%;">
        <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
        <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">Contact us |</a>
        <a href="{{url_for('home.homepage')}}" style="color: white;">Log out</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>

        <div style="position: fixed;
        bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;">
          
          <div style="position: fixed;
               bottom: 50%;
               left: 5%;
              width: 35%;
   
               background-color: #F2F2F2;text-align: center;
               font-size:xx-large;">
                ARTICLES
            </div>
            <div style="position: fixed;
              bottom: 26.5%;
              left: 12%;
              width: 20%;
              "
              >
               <img src="{{url_for('static', filename='article 1.png')}}" align="centre" style="width:200px;height:200px;" /> 
            </div>

            <div style="position: fixed;
              bottom: 25.5%;
              left: 23%;
              width:11.5%;height:23%;
              background-color: white ;
              border-radius: 30%; border-style: solid; border-color: white;padding-top: 4%;"
              >
              <div style="text-align: center;">
                <a href="https://www.indeed.com/career-advice/interviewing/how-to-prepare-for-an-interview" style="color: black; font-size: large;">How to prepare for an interview</a>
              </div>
            </div>

            <div style="position: fixed;
              bottom: 3%;
              left: 12%;
              width:11.5%;height:23%;
              background-color: white ;
              border-radius: 30%; border-style: solid; border-color: white;padding-top: 4%;"
              >
              <div style="text-align: center;">
                <a href="https://www.topuniversities.com/student-info/health-and-support/exam-preparation-ten-study-tips" style="color: black; font-size: large;">Exam Preparation:Ten Study Tips</a>
              </div>
            </div>

            <div style="position: fixed;
              bottom: 3%;
              left: 23.5%;
              width: 20%;
              "
              >
               <img src="{{url_for('static', filename='article2.png')}}" align="centre" style="width:210px;height:210px;" /> 
            </div>
        </div>

        <div style="position: fixed;
        bottom: 2%;
        right: 3%;
        width: 50%;
        height: 90%;
        background-color: #f2f2f2;">        

          <div style="position: fixed; top: 15%;
          right: 23%;
         width: 10%;
          height: 20%;
          border-radius: 100%;
          border-style: solid;
          border-color: grey;
          background-color: #a79ea0;text-align: center;
          font-size:xx-large;" >
          <img src="{{url_for('static', filename='IMG20180725121727.jpg')}}" align="centre" style="width:200px;height:200px;" /> 
  
        </div>
          <div style="position: fixed;
          top: 40%;
          right: 7%;
         width: 40%;
          height: 5%;
          background-color: #FF7994;text-align: center;
          font-size:xx-large;">
           WELCOME NICETA
          </div>

          <div style="position: fixed;
          bottom: 20%;
              right: 3%;
              width: 50%;">
          <div class="d-flex justify-content-center">

            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('opportunity.internships')}}" style="color: white;">Internships</a></button>
          </div>
          <div class="d-flex justify-content-center">
    
            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('opportunity.bursary')}}" style="color: white;">Bursaries</a></button>
          </div>
          <div class="d-flex justify-content-center">
    
            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('opportunity.grad')}}" style="color: white;">Graduate Programs</a></button>
          </div>
          <div class="d-flex justify-content-center">
    
            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('opportunity.shadowing')}}" style="color: white;">Job Shadowing</a></button>

          </div>
          </div>

          <div class="d-flex justify-content-center">
    <div style="position: fixed;
    bottom: 10%;
        right: 3%;
        width: 30%;">
            <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('student.network')}}" style="color: white;">Network</a></button>
          </div>
        </div>
        </div>
      </body>

</html>

app/templates/institution.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 20%;">
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">Contact us |</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>
        <div style="position: fixed;
         bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;">
          <div style="position: fixed; left: 15%; width: 50%; height: 45%;" >
            <img src="{{url_for('static', filename='Institution.png')}}" align="centre" style="width:400px;height:400px;" />
          </div>
        </div>

        <div style="position: fixed;
        bottom: 2%;
        right: 3%;
        width: 50%;
        height: 90%;
        background-color: #f2f2f2;">
           <div style="position: fixed;
              bottom: 2%;
              right: 3%;
              width: 50%;
              height: 90%;
              background-color: #f2f2f2;
              text-align: center;">
               <div style="position: fixed;
               top: 10%;
               right: 7%;
              width: 40%;
               height: 5%;
               background-color: #FF7994;text-align: center;
               font-size:xx-large;">
                INSTITUTION SIGN-UP
               </div>
              <div class="container" style=" width: 80%; padding: 2em; border-radius: 25px; border-width: thin; border-style: solid; margin-top: 10%;">
                <div class="container" style="width: 100%; padding: 5% 5%;">

                  <form action="{{ url_for('home.institution_register') }}" method="POST">

                    <div class="form-group">
                      <input type="text" class="form-control" name="name" placeholder="Name">
                    </div>              

                    <div class="form-group">
                      <input type="text" class="form-control" name="website" placeholder="Website">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="email" placeholder="Email">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="location" placeholder="Location">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="password" placeholder="Password">
                    </div>

                    <div class="d-flex justify-content-center">

                      <button type="submit" class="btn btn-info" style="margin-top: 2%;">SIGN UP</button>
                    </div>

                  </form>
                </div>
        </div>
      </body>

</html>

app/templates/mentor.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 20%;">
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
      <a href="{{url_for('home.register')}}" style="color: white;">Contact us</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>

        <div style="position: fixed;
        bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;">
          <div style="position: fixed; left: 15%; width: 50%; height: 45%;" >
           <img src="{{url_for('static', filename='Mentor.png')}}" align="centre" style="width:400px;height:400px;" />
        </div>
        </div>

        <div style="position: fixed;
        bottom: 2%;
        right: 3%;
        width: 50%;
        height: 90%;
        background-color: #f2f2f2;">
           <div style="position: fixed;
              bottom: 2%;
              right: 3%;
              width: 50%;
              height: 90%;
              background-color: #f2f2f2;
              text-align: center;">
               <div style="position: fixed;
               top: 10%;
               right: 7%;
              width: 40%;
               height: 5%;
               background-color: #FF7994;text-align: center;
               font-size:xx-large;">
                MENTOR SIGN-UP
               </div>
        <div class="container" style=" width: 80%; padding: 2em; border-radius: 25px; border-width: thin; border-style: solid; margin-top: 10%;">
  
                  <form action="{{ url_for('home.professional_register') }}" method="POST">
                    <div class="form-group">
                      <input type="text" class="form-control" name="name" placeholder="Name">
                    </div>              

                    <div class="form-group">
                      <input type="text" class="form-control" name="surname" placeholder="Surname">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="company" placeholder="Company">
                    </div>


                    <div class="form-group">
                      <input type="text" class="form-control" name="contact" placeholder="E-mail">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="website" placeholder="Website">

                    <div class="form-group">
                      <input type="text" class="form-control" name="location" placeholder="Location">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="linkedIn" placeholder="LinkedIn">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" name="password" placeholder="Password">
                    </div>

                    </div>
                    <div class="form-group">

                      <label for="Interests">Interests: </label>
                      <select class="form-group col-3" name="tag">
                        <option type="checkbox" id="tag1" name="tag1">
                        <label for="tag1"> Travelling</label>
                        <option type="checkbox" id="tag2" name="tag2">
                        <label for="tag2"> IoT</label>
                        <option type="checkbox" id="tag3" name="tag3">
                        <label for="tag3"> Art</label>
                        <option type="checkbox" id="tag4" name="tag4">
                        <label for="tag4"> Sports</label>
                      </select>
                    </div>

                    <div class="d-flex justify-content-center">

                      <button type="submit" class="btn btn-info" style="margin-top: 2%;">SIGN UP</button>
                    </div>

                  </form>
                </div>
        </div>
      </body>

</html>

app/templates/signup.html
<html>
  <head>
      <title>nextstep</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     
    </head>
    <body background="{{ url_for('static', filename='background.jpg') }}" >
      
      <header style="height: 50px; background-color: black;">
        <div style="text-align: right; color: white;font-weight: 100; font-size: xx-large;width: 50%;">NEXTSTEP</div>
      <div style="position: fixed; 
      right:1%;
      top: 0.5%;
      text-align: right; 
      
      font-weight: 100; 
      font-size: xx-large;
      width: 20%;">
      <a href="{{url_for('home.register')}}" style="color: white; padding-right: 2%;">About |</a>
      <a href="{{url_for('home.register')}}" style="color: white;">Contact us</a>
    </div>  
      
    </header>
          <div style="width: 48%; height: 50%; text-align: center;">
            
      <img src="{{url_for('static', filename='Capture.PNG')}}" align="centre" style="width:350px;height:350px;bottom: 10%;" /> 
          </div>

        <div style="position: fixed;
         bottom: 2.5%;
             left: 2%;
             width: 50%;
              height: 55%;
              padding-right: 6%;
              padding-top: 3%;
        background-color: #CDECF3;
        text-align: center;">
          <h2>WHO ARE YOU?</h2>
          
            <div class="d-flex justify-content-center">
      
              <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('home.student_register')}}" style="color: white;">Student</a></button>
            </div>
            <div class="d-flex justify-content-center">
      
              <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('home.professional_register')}}" style="color: white;">Mentor</a></button>
            </div>
            <div class="d-flex justify-content-center">
      
              <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('home.institution_register')}}" style="color: white;">Company</a></button>
            </div>
            <div class="d-flex justify-content-center">
      
              <button type="submit" class="btn btn-info" style="margin-top: 2%;background-color: black; width: 35%;font-size: x-large;"><a href="{{url_for('home.institution_register')}}" style="color: white;">Academic Institution</a></button>
            </div>
          </br>
          <p>Already have an account? <a href="{{url_for('home.login')}}">SIGN IN</a></p>
            </div>

            <div style="position: fixed;
            bottom: 2%;
            right: 3%;
            width: 50%;
            height: 90%;
            background-color: #f2f2f2;
            text-align: center;">
             <div style="position: fixed;
             top: 10%;
             right: 7%;
            width: 40%;
             height: 5%;
             background-color: #FF7994;text-align: center;
             font-size:xx-large;">
              YOUR FUTURE AWAITS
             </div>
             <div style="position: fixed;
             top: 22%;
             right: 3%;
             width: 50%;
             height: 30%;
             background-color: #f2f2f2;
             text-align: center;">
             <h3>Welcome to nextstep!</h3>
            </br>
          </br>
            <h4>Join us to find your next bursary, internship or future career...</h4>
             </div>
            <div style="position: fixed;
            bottom: 5%;
            right: 3%;
            width: 50%;"
            >
             <img src="{{url_for('static', filename='signin.png')}}" align="centre" style="width:500px;height:500px;" /> 
            </div>
            </div>
          </body>
      </body>

</html>